sudo: required

services:
  -docker

before_install:
  - docker build -t aikyab4u/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aikyab4u/react-test npm test

after_success:
  - docker build -t aikyab4u/multi-client ./client
  - docker build -t aikyab4u/multi-nginx ./nginx
  - docker build -t aikyab4u/multi-server ./server
  - docker build -t aikyab4u/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push aikyab4u/multi-client
  - docker push aikyab4u/multi-nginx
  - docker push aikyab4u/multi-server
  - docker push aikyab4u/multi-worker